apiVersion: v1
kind: Template
labels:
  template: jenkins-slave-swarm-maven
metadata:
  annotations:
    description: Creates a Jenkins slave image with swarm client connection
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-slave-swarm-maven
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: SLAVE_REPO_URL
  value: https://github.com/jr00n/jenkins-swarm.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: SLAVE_REPO_CONTEXTDIR
  value: slave
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: SLAVE_REPO_REF
  value: master
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-slave-swarm-maven
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-slave-swarm-maven
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-slave-swarm-maven:latest
    resources: {}
    source:
      contextDir: ${SLAVE_REPO_CONTEXTDIR}
      git:
        ref: ${SLAVE_REPO_REF}
        uri: ${SLAVE_REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - type: ConfigChange
